;; This file contains all package management for my emacs configuration
;; (done with use-package)

(require 'j-buffer-move)
(require 'j-company)
(require 'j-function-args)
(require 'j-git-gutter+)
(require 'j-helm)
(require 'j-multiple-cursors)
(require 'j-shell-pop)
(require 'j-smooth-scrolling)
(require 'j-solarized)
(require 'j-sr-speedbar)
(require 'j-ssh)
(require 'j-symon)
(require 'j-undo-tree)
(require 'j-wttrin)
